// Irish Makers Data - Dummy data for demo purposes

export const craftTypes = [
  "Pottery",
  "Textiles",
  "Jewelry",
  "Woodwork",
  "Glasswork",
  "Leatherwork",
  "Metalwork",
  "Painting",
];

export const counties = [
  "Sligo",
  "Donegal",
  "Mayo",
  "Galway",
  "Clare",
  "Kerry",
  "Cork",
  "Waterford",
  "Wexford",
  "Wicklow",
  "Dublin",
  "Meath",
  "Louth",
  "Monaghan",
  "Cavan",
  "Leitrim",
];

export const makers = [
  {
    id: 1,
    name: "Shane Mitchell",
    craftType: "Pottery",
    county: "Sligo",
    bio: "Creating functional pottery inspired by the wild Atlantic coast. Each piece is hand-thrown and glazed with minerals from the surrounding landscape.",
    avatar: "/inis-stor/shane.png",
    products: [
      {
        id: 101,
        name: "Atlantic Wave Bowl",
        description: "Hand-thrown ceramic bowl with wave-inspired glaze patterns",
        price: 65,
        image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400",
      },
      {
        id: 102,
        name: "Coastal Mug Set",
        description: "Set of 4 mugs featuring ocean-blue glazes",
        price: 85,
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400",
      },
      {
        id: 103,
        name: "Seashore Vase",
        description: "Tall vase with textured surface reminiscent of weathered cliffs",
        price: 95,
        image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400",
      },
    ],
  },
  {
    id: 2,
    name: "Aoife Ní Bhriain",
    craftType: "Textiles",
    county: "Donegal",
    bio: "Weaving traditional Irish patterns with contemporary flair. Using locally sourced wool and natural dyes from the Donegal hills.",
    avatar: "https://i.pravatar.cc/150?img=1",
    products: [
      {
        id: 201,
        name: "Donegal Tweed Scarf",
        description: "Hand-woven scarf in traditional Donegal patterns",
        price: 120,
        image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400",
      },
      {
        id: 202,
        name: "Wool Throw Blanket",
        description: "Luxurious throw blanket with Celtic knot motifs",
        price: 285,
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400",
      },
      {
        id: 203,
        name: "Merino Wool Cushion",
        description: "Soft cushion cover with geometric Irish patterns",
        price: 75,
        image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400",
      },
      {
        id: 204,
        name: "Hand-Dyed Yarn Bundle",
        description: "Collection of naturally dyed yarns in earthy tones",
        price: 45,
        image: "https://images.unsplash.com/photo-1606137548299-97c0f1a42c7d?w=400",
      },
    ],
  },
  {
    id: 3,
    name: "Ciarán O'Sullivan",
    craftType: "Jewelry",
    county: "Mayo",
    bio: "Crafting contemporary jewelry inspired by ancient Celtic designs. Each piece tells a story of Ireland's rich heritage.",
    avatar: "https://i.pravatar.cc/150?img=12",
    products: [
      {
        id: 301,
        name: "Celtic Knot Pendant",
        description: "Sterling silver pendant with intricate Celtic knotwork",
        price: 145,
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400",
      },
      {
        id: 302,
        name: "Claddagh Ring",
        description: "Traditional Claddagh ring in 14k gold",
        price: 320,
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400",
      },
      {
        id: 303,
        name: "Trinity Knot Earrings",
        description: "Delicate earrings featuring the trinity symbol",
        price: 95,
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400",
      },
    ],
  },
  {
    id: 4,
    name: "Siobhán Murphy",
    craftType: "Woodwork",
    county: "Galway",
    bio: "Turning ancient Irish oak into functional art. Every grain tells a story of the forests that once covered this land.",
    avatar: "https://i.pravatar.cc/150?img=5",
    products: [
      {
        id: 401,
        name: "Oak Serving Board",
        description: "Hand-carved serving board from reclaimed Irish oak",
        price: 110,
        image: "https://images.unsplash.com/photo-1565183928294-7d22f2d8c29b?w=400",
      },
      {
        id: 402,
        name: "Wooden Bowl Set",
        description: "Nested bowls turned from local ash wood",
        price: 165,
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400",
      },
      {
        id: 403,
        name: "Celtic Cross Wall Art",
        description: "Carved wall hanging featuring traditional Celtic cross",
        price: 225,
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=400",
      },
      {
        id: 404,
        name: "Whiskey Barrel Coasters",
        description: "Coaster set made from reclaimed whiskey barrels",
        price: 55,
        image: "https://images.unsplash.com/photo-1595855759920-86582396756e?w=400",
      },
    ],
  },
  {
    id: 5,
    name: "Liam McCarthy",
    craftType: "Glasswork",
    county: "Clare",
    bio: "Blowing glass in the tradition of Irish crystal makers. Each piece captures the light of the Burren landscape.",
    avatar: "https://i.pravatar.cc/150?img=13",
    products: [
      {
        id: 501,
        name: "Crystal Whiskey Glasses",
        description: "Hand-blown whiskey glasses with Celtic cut patterns",
        price: 185,
        image: "https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=400",
      },
      {
        id: 502,
        name: "Stained Glass Panel",
        description: "Decorative panel featuring Irish landscape motifs",
        price: 340,
        image: "https://images.unsplash.com/photo-1582035541319-3338f0e114f4?w=400",
      },
      {
        id: 503,
        name: "Glass Votive Holders",
        description: "Set of 3 hand-blown votive candle holders",
        price: 75,
        image: "https://images.unsplash.com/photo-1602874801006-c2b1a6c2d8cf?w=400",
      },
    ],
  },
  {
    id: 6,
    name: "Niamh O'Connor",
    craftType: "Leatherwork",
    county: "Kerry",
    bio: "Hand-stitching leather goods using traditional techniques passed down through generations. Quality that lasts a lifetime.",
    avatar: "https://i.pravatar.cc/150?img=9",
    products: [
      {
        id: 601,
        name: "Leather Journal",
        description: "Hand-bound journal with Celtic embossing",
        price: 95,
        image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400",
      },
      {
        id: 602,
        name: "Messenger Bag",
        description: "Full-grain leather bag with brass hardware",
        price: 285,
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
      },
      {
        id: 603,
        name: "Wallet with Celtic Design",
        description: "Bifold wallet with hand-tooled Celtic patterns",
        price: 75,
        image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
      },
      {
        id: 604,
        name: "Leather Bracelet",
        description: "Braided leather bracelet with silver clasp",
        price: 45,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400",
      },
    ],
  },
  {
    id: 7,
    name: "Seán Fitzgerald",
    craftType: "Metalwork",
    county: "Cork",
    bio: "Forging iron and steel in the old way. Creating pieces that blend ancient Celtic artistry with modern functionality.",
    avatar: "https://i.pravatar.cc/150?img=14",
    products: [
      {
        id: 701,
        name: "Wrought Iron Candle Holder",
        description: "Hand-forged candle holder with spiral design",
        price: 125,
        image: "https://images.unsplash.com/photo-1602874801006-c2b1a6c2d8cf?w=400",
      },
      {
        id: 702,
        name: "Celtic Door Knocker",
        description: "Bronze door knocker with trinity knot design",
        price: 165,
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
      },
      {
        id: 703,
        name: "Fire Poker Set",
        description: "Hand-forged fireplace tools with Celtic details",
        price: 245,
        image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400",
      },
    ],
  },
  {
    id: 8,
    name: "Róisín Kelly",
    craftType: "Painting",
    county: "Waterford",
    bio: "Capturing the ever-changing light of the Irish coast. My paintings celebrate the raw beauty of our island home.",
    avatar: "https://i.pravatar.cc/150?img=10",
    products: [
      {
        id: 801,
        name: "Coastal Sunrise Print",
        description: "Limited edition print of Waterford coastline at dawn",
        price: 85,
        image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400",
      },
      {
        id: 802,
        name: "Irish Cottage Original",
        description: "Original oil painting of traditional thatched cottage",
        price: 650,
        image: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=400",
      },
      {
        id: 803,
        name: "Stormy Seas Canvas",
        description: "Large canvas depicting Atlantic storm",
        price: 425,
        image: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
      },
      {
        id: 804,
        name: "Wildflower Meadow",
        description: "Watercolor painting of Irish wildflowers",
        price: 195,
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
      },
    ],
  },
  {
    id: 9,
    name: "Pádraig Walsh",
    craftType: "Pottery",
    county: "Wexford",
    bio: "Creating rustic pottery that brings the warmth of the Irish hearth to your home. Each piece is unique and functional.",
    avatar: "https://i.pravatar.cc/150?img=15",
    products: [
      {
        id: 901,
        name: "Farmhouse Butter Crock",
        description: "Traditional butter keeper with Celtic motifs",
        price: 55,
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400",
      },
      {
        id: 902,
        name: "Rustic Dinner Set",
        description: "4-piece place setting in earthy tones",
        price: 145,
        image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400",
      },
      {
        id: 903,
        name: "Herb Planter Trio",
        description: "Set of 3 planters perfect for kitchen herbs",
        price: 75,
        image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400",
      },
    ],
  },
  {
    id: 10,
    name: "Aisling Ryan",
    craftType: "Textiles",
    county: "Wicklow",
    bio: "Weaving stories into fabric. My textiles blend traditional Irish patterns with contemporary design sensibilities.",
    avatar: "https://i.pravatar.cc/150?img=20",
    products: [
      {
        id: 1001,
        name: "Linen Table Runner",
        description: "Hand-woven linen runner with Celtic border",
        price: 95,
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400",
      },
      {
        id: 1002,
        name: "Wool Tapestry",
        description: "Wall tapestry depicting Irish mythology",
        price: 385,
        image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400",
      },
      {
        id: 1003,
        name: "Embroidered Cushions",
        description: "Pair of cushions with hand-embroidered shamrocks",
        price: 125,
        image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400",
      },
      {
        id: 1004,
        name: "Irish Linen Tea Towels",
        description: "Set of 3 tea towels with traditional patterns",
        price: 45,
        image: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400",
      },
    ],
  },
  {
    id: 11,
    name: "Tadhg O'Brien",
    craftType: "Jewelry",
    county: "Dublin",
    bio: "Modern interpretations of ancient Irish jewelry. Each piece connects the wearer to thousands of years of Celtic tradition.",
    avatar: "https://i.pravatar.cc/150?img=33",
    products: [
      {
        id: 1101,
        name: "Newgrange Spiral Necklace",
        description: "Silver necklace inspired by Newgrange carvings",
        price: 175,
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400",
      },
      {
        id: 1102,
        name: "Tara Brooch Replica",
        description: "Detailed replica of the famous Tara Brooch",
        price: 295,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400",
      },
      {
        id: 1103,
        name: "Ogham Script Bracelet",
        description: "Bracelet engraved with ancient Ogham writing",
        price: 135,
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400",
      },
    ],
  },
  {
    id: 12,
    name: "Mairéad Doyle",
    craftType: "Woodwork",
    county: "Meath",
    bio: "Carving the spirit of ancient Ireland into every piece. My work celebrates the sacred trees of Celtic tradition.",
    avatar: "https://i.pravatar.cc/150?img=24",
    products: [
      {
        id: 1201,
        name: "Ogham Walking Stick",
        description: "Hand-carved walking stick with Ogham inscriptions",
        price: 165,
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=400",
      },
      {
        id: 1202,
        name: "Celtic Jewelry Box",
        description: "Intricate jewelry box with Celtic carvings",
        price: 195,
        image: "https://images.unsplash.com/photo-1595855759920-86582396756e?w=400",
      },
      {
        id: 1203,
        name: "Wooden Harp Ornament",
        description: "Miniature Irish harp carved from bog oak",
        price: 85,
        image: "https://images.unsplash.com/photo-1565183928294-7d22f2d8c29b?w=400",
      },
      {
        id: 1204,
        name: "Tree of Life Wall Panel",
        description: "Large carved panel featuring the Celtic tree of life",
        price: 425,
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=400",
      },
    ],
  },
  {
    id: 13,
    name: "Oisín Byrne",
    craftType: "Glasswork",
    county: "Louth",
    bio: "Transforming molten glass into pieces that capture the essence of Irish light and landscape.",
    avatar: "https://i.pravatar.cc/150?img=52",
    products: [
      {
        id: 1301,
        name: "Celtic Knot Paperweight",
        description: "Hand-blown glass paperweight with embedded Celtic design",
        price: 95,
        image: "https://images.unsplash.com/photo-1602874801006-c2b1a6c2d8cf?w=400",
      },
      {
        id: 1302,
        name: "Irish Landscape Bowl",
        description: "Decorative bowl with swirling green and blue glass",
        price: 245,
        image: "https://images.unsplash.com/photo-1582035541319-3338f0e114f4?w=400",
      },
      {
        id: 1303,
        name: "Shamrock Sun Catcher",
        description: "Stained glass shamrock for windows",
        price: 65,
        image: "https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=400",
      },
    ],
  },
  {
    id: 14,
    name: "Caoimhe Lynch",
    craftType: "Leatherwork",
    county: "Monaghan",
    bio: "Crafting leather goods with precision and care. Every stitch honors the tradition of Irish craftsmanship.",
    avatar: "https://i.pravatar.cc/150?img=26",
    products: [
      {
        id: 1401,
        name: "Celtic Belt",
        description: "Hand-tooled leather belt with Celtic patterns",
        price: 115,
        image: "https://images.unsplash.com/photo-1624222247344-550fb60583b2?w=400",
      },
      {
        id: 1402,
        name: "Leather Satchel",
        description: "Traditional Irish satchel in vegetable-tanned leather",
        price: 325,
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
      },
      {
        id: 1403,
        name: "Card Holder",
        description: "Slim card holder with shamrock embossing",
        price: 45,
        image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
      },
      {
        id: 1404,
        name: "Leather Key Fob",
        description: "Durable key fob with Celtic knot design",
        price: 35,
        image: "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400",
      },
    ],
  },
  {
    id: 15,
    name: "Fionn MacCarthy",
    craftType: "Metalwork",
    county: "Cavan",
    bio: "Forging metal into art. My work bridges the gap between ancient Celtic metalworking and contemporary design.",
    avatar: "https://i.pravatar.cc/150?img=60",
    products: [
      {
        id: 1501,
        name: "Bronze Celtic Cross",
        description: "Hand-cast bronze cross with intricate knotwork",
        price: 185,
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
      },
      {
        id: 1502,
        name: "Iron Wall Sconce",
        description: "Hand-forged wall sconce with spiral design",
        price: 145,
        image: "https://images.unsplash.com/photo-1602874801006-c2b1a6c2d8cf?w=400",
      },
      {
        id: 1503,
        name: "Copper Bowl",
        description: "Hammered copper bowl with Celtic rim pattern",
        price: 195,
        image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400",
      },
    ],
  },
  {
    id: 16,
    name: "Saoirse Quinn",
    craftType: "Painting",
    county: "Leitrim",
    bio: "Painting the soul of Ireland. My work explores the mystical connection between land, water, and sky.",
    avatar: "https://i.pravatar.cc/150?img=45",
    products: [
      {
        id: 1601,
        name: "Lough Gill Reflection",
        description: "Original acrylic painting of Lough Gill",
        price: 485,
        image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400",
      },
      {
        id: 1602,
        name: "Celtic Knot Series",
        description: "Set of 3 prints featuring modern Celtic designs",
        price: 125,
        image: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=400",
      },
      {
        id: 1603,
        name: "Misty Morning",
        description: "Watercolor of Irish countryside in morning fog",
        price: 165,
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
      },
      {
        id: 1604,
        name: "Ancient Stones",
        description: "Oil painting of megalithic stone circle",
        price: 575,
        image: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
      },
    ],
  },
  // Additional makers to support clustering (duplicates in same counties)
  {
    id: 17,
    name: "Declan O'Malley",
    craftType: "Pottery",
    county: "Sligo",
    bio: "Specializing in raku-fired ceramics inspired by ancient Irish pottery traditions.",
    avatar: "https://i.pravatar.cc/150?img=17",
    products: [
      {
        id: 1701,
        name: "Raku Tea Bowl",
        description: "Hand-formed tea bowl with crackle glaze",
        price: 75,
        image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400",
      },
      {
        id: 1702,
        name: "Celtic Platter",
        description: "Large serving platter with Celtic designs",
        price: 125,
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400",
      },
      {
        id: 1703,
        name: "Stoneware Pitcher",
        description: "Functional pitcher with natural ash glaze",
        price: 95,
        image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400",
      },
    ],
  },
  {
    id: 18,
    name: "Brigid Flanagan",
    craftType: "Textiles",
    county: "Donegal",
    bio: "Creating contemporary Irish textiles with traditional weaving methods.",
    avatar: "https://i.pravatar.cc/150?img=18",
    products: [
      {
        id: 1801,
        name: "Aran Knit Blanket",
        description: "Hand-knitted blanket in traditional Aran patterns",
        price: 295,
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400",
      },
      {
        id: 1802,
        name: "Wool Shawl",
        description: "Lightweight shawl in heathered tones",
        price: 145,
        image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400",
      },
      {
        id: 1803,
        name: "Table Runner",
        description: "Woven table runner with Celtic border",
        price: 85,
        image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400",
      },
    ],
  },
  {
    id: 19,
    name: "Colm Brennan",
    craftType: "Woodwork",
    county: "Galway",
    bio: "Crafting heirloom furniture from reclaimed Irish timber.",
    avatar: "https://i.pravatar.cc/150?img=19",
    products: [
      {
        id: 1901,
        name: "Oak Dining Table",
        description: "Handcrafted table from 200-year-old oak",
        price: 1850,
        image: "https://images.unsplash.com/photo-1565183928294-7d22f2d8c29b?w=400",
      },
      {
        id: 1902,
        name: "Wooden Spoon Set",
        description: "Hand-carved spoons from native woods",
        price: 65,
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400",
      },
      {
        id: 1903,
        name: "Cutting Board",
        description: "End-grain cutting board in mixed woods",
        price: 95,
        image: "https://images.unsplash.com/photo-1595855759920-86582396756e?w=400",
      },
    ],
  },
  {
    id: 20,
    name: "Grainne Murphy",
    craftType: "Jewelry",
    county: "Dublin",
    bio: "Modern Irish jewelry inspired by Book of Kells illuminations.",
    avatar: "https://i.pravatar.cc/150?img=21",
    products: [
      {
        id: 2001,
        name: "Illuminated Pendant",
        description: "Silver pendant with enamel details",
        price: 195,
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400",
      },
      {
        id: 2002,
        name: "Celtic Bangle",
        description: "Hand-forged bronze bangle with knotwork",
        price: 145,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400",
      },
      {
        id: 2003,
        name: "Spiral Earrings",
        description: "Gold earrings with triple spiral motif",
        price: 125,
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400",
      },
    ],
  },
  {
    id: 21,
    name: "Eamon Gallagher",
    craftType: "Pottery",
    county: "Cork",
    bio: "Creating functional pottery with a focus on sustainability and local materials.",
    avatar: "https://i.pravatar.cc/150?img=22",
    products: [
      {
        id: 2101,
        name: "Coffee Mug Set",
        description: "Set of 4 handmade mugs in earth tones",
        price: 85,
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400",
      },
      {
        id: 2102,
        name: "Salad Bowl",
        description: "Large serving bowl with natural glaze",
        price: 95,
        image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400",
      },
      {
        id: 2103,
        name: "Vase Collection",
        description: "Set of 3 bud vases in varying heights",
        price: 75,
        image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400",
      },
    ],
  },
  {
    id: 22,
    name: "Maeve O'Donnell",
    craftType: "Painting",
    county: "Kerry",
    bio: "Landscape painter capturing the dramatic beauty of the Kerry coastline.",
    avatar: "https://i.pravatar.cc/150?img=23",
    products: [
      {
        id: 2201,
        name: "Skellig Sunset",
        description: "Original oil painting of Skellig Michael",
        price: 725,
        image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400",
      },
      {
        id: 2202,
        name: "Ring of Kerry Print",
        description: "Limited edition print of coastal landscape",
        price: 95,
        image: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=400",
      },
      {
        id: 2203,
        name: "Mountain View",
        description: "Watercolor of MacGillycuddy's Reeks",
        price: 185,
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
      },
    ],
  },
  {
    id: 23,
    name: "Ronan Fitzgerald",
    craftType: "Glasswork",
    county: "Waterford",
    bio: "Continuing Waterford's crystal tradition with contemporary designs.",
    avatar: "https://i.pravatar.cc/150?img=25",
    products: [
      {
        id: 2301,
        name: "Crystal Decanter",
        description: "Hand-cut crystal decanter with Celtic pattern",
        price: 295,
        image: "https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=400",
      },
      {
        id: 2302,
        name: "Wine Glass Set",
        description: "Set of 6 hand-blown wine glasses",
        price: 245,
        image: "https://images.unsplash.com/photo-1602874801006-c2b1a6c2d8cf?w=400",
      },
      {
        id: 2303,
        name: "Glass Sculpture",
        description: "Abstract sculpture in blue and green glass",
        price: 425,
        image: "https://images.unsplash.com/photo-1582035541319-3338f0e114f4?w=400",
      },
    ],
  },
  {
    id: 24,
    name: "Sinead Kelly",
    craftType: "Leatherwork",
    county: "Wicklow",
    bio: "Handcrafting leather goods using traditional Irish tanning methods.",
    avatar: "https://i.pravatar.cc/150?img=27",
    products: [
      {
        id: 2401,
        name: "Leather Tote",
        description: "Large tote bag in vegetable-tanned leather",
        price: 265,
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
      },
      {
        id: 2402,
        name: "Belt with Celtic Buckle",
        description: "Hand-tooled belt with bronze buckle",
        price: 125,
        image: "https://images.unsplash.com/photo-1624222247344-550fb60583b2?w=400",
      },
      {
        id: 2403,
        name: "Passport Holder",
        description: "Compact passport holder with embossing",
        price: 55,
        image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
      },
    ],
  },
];

