/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 soolax.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/soolax.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
    </group>
  )
}

useGLTF.preload('/soolax.glb')
