/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ireland.glb --transform --keepmeshes --keepmaterials 
Files: ireland.glb [16.05MB] > /Users/thomasgertenbach/Documents/GitHub/playground/public/inis-stor/ireland-transformed.glb [871.37KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ireland-transformed.glb')

  console.log(first)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sea.geometry} material={nodes.sea.material} />
      <mesh geometry={nodes['ireland-map'].geometry} material={materials['Material.002']} />
      <mesh geometry={nodes['edge-map'].geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh geometry={nodes.babysheep.geometry} material={materials.Sheep} />
      <mesh geometry={nodes.fence.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.mommysheep.geometry} material={materials.Sheep} />
      <mesh geometry={nodes.cloud1.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.cloud2.geometry} material={materials['Scene_-_Root']} />
    </group>
  )
}

useGLTF.preload('/ireland-transformed.glb')
